sudo: false
language: c
addons:
    apt:
        packages:
            - cmake
            - valgrind
            - gcc
script:
    - cmake .
    - make
    - make test
    - valgrind --leak-check=full --error-exitcode=1 ./test_list
